import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<string, Record<Language, string>> = {
  "app.name": { en: "Quizora", ar: "Quizora" },
  "app.copyright": { en: "© 2026 Quizora. All rights reserved.", ar: "© 2026 Quizora. جميع الحقوق محفوظة." },
  "common.back": { en: "Back", ar: "رجوع" },
  "common.save": { en: "Save", ar: "حفظ" },
  "common.cancel": { en: "Cancel", ar: "إلغاء" },
  "common.loading": { en: "Loading...", ar: "جاري التحميل..." },
  "common.view": { en: "View", ar: "عرض" },
  "common.start": { en: "Start", ar: "ابدأ" },
  "common.share": { en: "Share", ar: "مشاركة" },
  "common.signOut": { en: "Sign Out", ar: "تسجيل خروج" },
  "common.settings": { en: "Settings", ar: "الإعدادات" },
  "nav.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "nav.learningTrack": { en: "Learning Track", ar: "مسار التعلم" },
  "nav.continueLearning": { en: "Continue Learning", ar: "متابعة التعلم" },
  "nav.results": { en: "Results", ar: "النتائج" },
  "nav.assessments": { en: "Assessments", ar: "التقييمات" },
  "nav.profile": { en: "My Profile", ar: "ملفي الشخصي" },
  "nav.reports": { en: "Reports", ar: "التقارير" },
  "landing.tagline": { en: "Your Path to success starts here", ar: "طريقك نحو النجاح يبدأ من هنا" },
  "landing.headline1": { en: "Professional Certifications & ", ar: "شهادات مهنية و " },
  "landing.headline2": { en: "Aptitude Platform", ar: "منصة اختبارات القدرات" },
  "landing.getStarted": { en: "Get Started", ar: "ابدأ الآن" },
  "landing.exploreLearning": { en: "Explore Learning Track", ar: "استكشف مسار التعلم" },
  "landing.whyChoose": { en: "Why Choose Our ", ar: "لماذا تختار " },
  "landing.platform": { en: "Platform?", ar: "منصتنا؟" },
  "landing.readyToStart": { en: "Ready to Start Your Learning Journey?", ar: "مستعد لبدء رحلة التعلم؟" },
  "landing.signUpFree": { en: "Sign Up for Free", ar: "سجّل مجاناً" },
  "landing.feat1Title": { en: "Professional Certifications", ar: "شهادات مهنية" },
  "landing.feat1Desc": { en: "Get certified in CCNA, Security+, AWS CCP, PMP with comprehensive training programs.", ar: "احصل على شهادات CCNA, Security+, AWS CCP, PMP مع برامج تدريبية شاملة." },
  "landing.feat2Title": { en: "Aptitude & Achievement Tests", ar: "اختبارات القدرات والتحصيلي" },
  "landing.feat2Desc": { en: "Prepare for Qudurat and Tahsili exams with specialized training courses.", ar: "استعد لاختبارات القدرات والتحصيلي مع دورات تدريبية متخصصة." },
  "landing.feat3Title": { en: "Detailed Reports", ar: "تقارير تفصيلية" },
  "landing.feat3Desc": { en: "Track your progress with accurate reports and comprehensive analytics to stay on top of your game.", ar: "تابع تقدمك بتقارير دقيقة وتحليلات شاملة." },
  "auth.accessDashboard": { en: "Access your learning dashboard", ar: "ادخل لوحة التعلم الخاصة بك" },
  "auth.signIn": { en: "Sign In", ar: "تسجيل الدخول" },
  "auth.signUp": { en: "Sign Up", ar: "إنشاء حساب" },
  "auth.welcomeBack": { en: "Welcome Back", ar: "مرحباً بعودتك" },
  "auth.enterCredentials": { en: "Enter your credentials to access your account", ar: "أدخل بياناتك للوصول إلى حسابك" },
  "auth.email": { en: "Email", ar: "البريد الإلكتروني" },
  "auth.password": { en: "Password", ar: "كلمة المرور" },
  "auth.enterEmail": { en: "Enter your email", ar: "أدخل بريدك الإلكتروني" },
  "auth.enterPassword": { en: "Enter your password", ar: "أدخل كلمة المرور" },
  "auth.forgotPassword": { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
  "auth.signingIn": { en: "Signing in...", ar: "جاري تسجيل الدخول..." },
  "auth.orContinueWith": { en: "Or continue with", ar: "أو تابع باستخدام" },
  "auth.createAccount": { en: "Create Account", ar: "إنشاء حساب" },
  "auth.fillDetails": { en: "Fill in your details to get started", ar: "أدخل بياناتك للبدء" },
  "auth.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "auth.enterFullName": { en: "Enter your full name", ar: "أدخل اسمك الكامل" },
  "auth.createPassword": { en: "Create a password", ar: "أنشئ كلمة مرور" },
  "auth.creatingAccount": { en: "Creating account...", ar: "جاري إنشاء الحساب..." },
  "auth.backToHome": { en: "Back to Home", ar: "العودة للرئيسية" },
  "auth.alreadyHaveAccount": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "auth.fillAllFields": { en: "Please fill in all fields.", ar: "يرجى ملء جميع الحقول." },
  "auth.signInFailed": { en: "Sign in failed", ar: "فشل تسجيل الدخول" },
  "auth.signedInSuccess": { en: "You have successfully signed in.", ar: "تم تسجيل دخولك بنجاح." },
  "auth.accountCreated": { en: "Account created!", ar: "تم إنشاء الحساب!" },
  "auth.emailVerification": { en: "Please check your email to verify your account.", ar: "يرجى التحقق من بريدك لتأكيد الحساب." },
  "auth.loginFailed": { en: "Login failed", ar: "فشل تسجيل الدخول" },
  "auth.enterEmailFirst": { en: "Please enter your email first.", ar: "يرجى إدخال بريدك الإلكتروني أولاً." },
  "auth.resetLinkSent": { en: "We sent you a password reset link.", ar: "أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك." },
  "reset.title": { en: "Reset Password", ar: "إعادة تعيين كلمة المرور" },
  "reset.enterNew": { en: "Enter your new password", ar: "أدخل كلمة المرور الجديدة" },
  "reset.newPassword": { en: "New Password", ar: "كلمة المرور الجديدة" },
  "reset.chooseStrong": { en: "Choose a strong password for your account", ar: "اختر كلمة مرور قوية لحسابك" },
  "reset.confirm": { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  "reset.confirmPlaceholder": { en: "Confirm new password", ar: "أكد كلمة المرور الجديدة" },
  "reset.newPlaceholder": { en: "New password", ar: "كلمة المرور الجديدة" },
  "reset.updating": { en: "Updating...", ar: "جاري التحديث..." },
  "reset.updatePassword": { en: "Update Password", ar: "تحديث كلمة المرور" },
  "dashboard.hub": { en: "Your learning hub", ar: "مركز التعلم الخاص بك" },
  "dashboard.learning": { en: "Learning", ar: "لوحة" },
  "dashboard.title": { en: "Dashboard", ar: "التحكم" },
  "dashboard.chooseOption": { en: "Choose one of the options below to continue your learning journey", ar: "اختر أحد الخيارات أدناه لمتابعة رحلة تعلمك" },
  "dashboard.learningTrack": { en: "Learning Track", ar: "مسار التعلم" },
  "dashboard.learningTrackDesc": { en: "Professional Certifications & Aptitude Tests", ar: "شهادات مهنية واختبارات القدرات" },
  "dashboard.questions": { en: "Questions", ar: "الأسئلة" },
  "dashboard.questionsDesc": { en: "Complete your assessment questionnaire", ar: "أكمل استبيان التقييم" },
  "dashboard.evaluation": { en: "Evaluation", ar: "التقييم" },
  "dashboard.evaluationDesc": { en: "View your scores and AI feedback", ar: "عرض درجاتك وملاحظات الذكاء الاصطناعي" },
  "dashboard.startNow": { en: "Start Now", ar: "ابدأ الآن" },
  "dashboard.continueLearning": { en: "Continue Learning", ar: "تابع تقدمك" },
  "dashboard.resumeWhereYouLeftOff": { en: "Resume where you left off", ar: "أكمل من حيث توقفت" },
  "dashboard.latestCourse": { en: "Continue your latest course", ar: "استمر في آخر دورة بدأت بها" },
  "dashboard.continueCourse": { en: "Continue Course", ar: "أكمل الدورة" },
  "dashboard.continueLearningDesc": { en: "Open the Continue Learning hub to resume any incomplete course.", ar: "افتح مركز المتابعة لاستئناف أي دورة غير مكتملة." },
  "dashboard.chooseCourseToContinue": { en: "Choose a course to continue", ar: "اختر دورة للاستمرار" },
  "dashboard.unfinishedCourses": { en: "unfinished course(s)", ar: "دورة غير مكتملة" },
  "dashboard.noProgressYet": { en: "Start a course to begin tracking progress", ar: "ابدأ دورة لتتبع تقدمك" },
  "dashboard.startNewCourse": { en: "Start a new course to save your progress here.", ar: "ابدأ دورة جديدة لحفظ تقدمك هنا." },
  "dashboard.completed": { en: "Completed", ar: "مكتمل" },
  "dashboard.lastActivity": { en: "Last activity", ar: "آخر نشاط" },
  "dashboard.loadingProgress": { en: "Loading your latest progress...", ar: "تحميل آخر تقدم..." },
  "dashboard.remainingQuestions": { en: "Remaining questions", ar: "الأسئلة المتبقية" },
  "dashboard.complete": { en: "Complete", ar: "مكتمل" },
  "dashboard.reportsAnalytics": { en: "Reports & Analytics", ar: "التقارير والتحليلات" },
  "dashboard.reportsDesc": { en: "View detailed reports and track your progress", ar: "عرض التقارير التفصيلية ومتابعة تقدمك" },
  "dashboard.viewReports": { en: "View Reports", ar: "عرض التقارير" },
  "dashboard.questionsAnswered": { en: "Questions Answered", ar: "أسئلة تم إجابتها" },
  "dashboard.avgScore": { en: "Avg Score", ar: "متوسط الدرجة" },
  "dashboard.studyTime": { en: "Study Time", ar: "وقت الدراسة" },
  "courses.choosePath": { en: "Choose your path", ar: "اختر مسارك" },
  "courses.whatPractice": { en: "What do you want to ", ar: "ماذا تريد أن " },
  "courses.practice": { en: "practice?", ar: "تتدرب عليه؟" },
  "courses.selectCategory": { en: "Select a category to begin your learning journey with adaptive, AI-powered practice.", ar: "اختر فئة لبدء رحلة تعلمك مع تدريب تكيفي مدعوم بالذكاء الاصطناعي." },
  "courses.backToCategories": { en: "Back to categories", ar: "العودة للفئات" },
  "courses.pickSubject": { en: "Pick a subject to start your quiz session.", ar: "اختر مادة لبدء جلسة الاختبار." },
  "courses.available": { en: "courses available", ar: "كورسات متاحة" },
  "courses.getStarted": { en: "Get Started", ar: "ابدأ" },
  "courses.startQuiz": { en: "Start Quiz", ar: "ابدأ الاختبار" },
  "courses.qudurat": { en: "Qudurat", ar: "القدرات" },
  "courses.quduratSub": { en: "General Aptitude Test", ar: "اختبار القدرات العامة" },
  "courses.quduratDesc": { en: "Prepare for the GAT with adaptive practice covering quantitative and verbal reasoning.", ar: "استعد لاختبار القدرات العامة مع تدريب تكيفي يغطي التفكير الكمي واللفظي." },
  "courses.tahseeli": { en: "Tahseeli", ar: "التحصيلي" },
  "courses.tahseeliSub": { en: "Achievement Test", ar: "اختبار التحصيلي" },
  "courses.tahseeliDesc": { en: "Master your subjects with targeted practice for the Saudi Achievement Test.", ar: "أتقن موادك مع تدريب موجّه لاختبار التحصيلي." },
  "courses.certifications": { en: "Professional Certifications", ar: "شهادات مهنية" },
  "courses.certificationsSub": { en: "IT & Management Certs", ar: "شهادات تقنية وإدارية" },
  "courses.certificationsDesc": { en: "Ace industry-leading certifications with expert-curated question banks.", ar: "اجتز الشهادات المهنية الرائدة مع بنوك أسئلة متخصصة." },
  "questions.sessionComplete": { en: "Session Complete! 🎉", ar: "اكتملت الجلسة! 🎉" },
  "questions.questionsLabel": { en: "Questions", ar: "أسئلة" },
  "questions.correct": { en: "Correct", ar: "صحيح" },
  "questions.accuracy": { en: "Accuracy", ar: "الدقة" },
  "questions.backToCourses": { en: "Back to Courses", ar: "العودة للكورسات" },
  "questions.viewReport": { en: "View Report", ar: "عرض التقرير" },
  "questions.adaptiveQuiz": { en: "Adaptive Quiz", ar: "اختبار تكيفي" },
  "questions.endSession": { en: "End Session", ar: "إنهاء الجلسة" },
  "questions.loadingQuestion": { en: "Loading question...", ar: "جاري تحميل السؤال..." },
  "questions.easy": { en: "Easy", ar: "سهل" },
  "questions.medium": { en: "Medium", ar: "متوسط" },
  "questions.hard": { en: "Hard", ar: "صعب" },
  "questions.correctAnswer": { en: "Correct Answer!", ar: "إجابة صحيحة!" },
  "questions.wrongAnswer": { en: "Wrong Answer", ar: "إجابة خاطئة" },
  "questions.generating": { en: "Generating...", ar: "جاري التوليد..." },
  "questions.showExplanation": { en: "Show Explanation", ar: "عرض الشرح" },
  "questions.checking": { en: "Checking...", ar: "جاري التحقق..." },
  "questions.submitAnswer": { en: "Submit Answer", ar: "إرسال الإجابة" },
  "questions.nextQuestion": { en: "Next Question", ar: "السؤال التالي" },
  "settings.title": { en: "Settings", ar: "الإعدادات" },
  "settings.subtitle": { en: "Manage your account preferences", ar: "إدارة تفضيلات حسابك" },
  "settings.language": { en: "Language", ar: "اللغة" },
  "settings.languageDesc": { en: "Choose your preferred language", ar: "اختر لغتك المفضلة" },
  "settings.changePassword": { en: "Change Password", ar: "تغيير كلمة المرور" },
  "settings.updateAccountPassword": { en: "Update your account password", ar: "تحديث كلمة المرور الخاصة بك" },
  "settings.currentPassword": { en: "Current Password", ar: "كلمة المرور الحالية" },
  "settings.enterCurrentPassword": { en: "Enter current password", ar: "أدخل كلمة المرور الحالية" },
  "settings.newPassword": { en: "New Password", ar: "كلمة المرور الجديدة" },
  "settings.enterNewPassword": { en: "Enter new password", ar: "أدخل كلمة المرور الجديدة" },
  "settings.confirmNewPassword": { en: "Confirm New Password", ar: "تأكيد كلمة المرور الجديدة" },
  "settings.confirmNewPasswordPlaceholder": { en: "Confirm new password", ar: "أكد كلمة المرور الجديدة" },
  "settings.updatePassword": { en: "Update Password", ar: "تحديث كلمة المرور" },
  "settings.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "settings.notifications": { en: "Notifications", ar: "الإشعارات" },
  "settings.controlEmails": { en: "Control what emails you receive", ar: "تحكم بالإيميلات التي تصلك" },
  "settings.emailNotifications": { en: "Email Notifications", ar: "إشعارات البريد الإلكتروني" },
  "settings.emailNotificationsDesc": { en: "Receive important updates via email", ar: "استقبل التحديثات المهمة عبر البريد الإلكتروني" },
  "settings.quizReminders": { en: "Quiz Reminders", ar: "تذكيرات الاختبار" },
  "settings.quizRemindersDesc": { en: "Get reminded to practice daily", ar: "احصل على تذكير للتدرب يومياً" },
  "settings.progressReports": { en: "Progress Reports", ar: "تقارير التقدم" },
  "settings.progressReportsDesc": { en: "Weekly summary of your performance", ar: "ملخص أسبوعي لأدائك" },
  "settings.savePreferences": { en: "Save Preferences", ar: "حفظ التفضيلات" },
  "settings.accountInfo": { en: "Account Info", ar: "معلومات الحساب" },
  "settings.yourAccountDetails": { en: "Your account details", ar: "تفاصيل حسابك" },
  "settings.emailAddress": { en: "Email Address", ar: "البريد الإلكتروني" },
  "settings.accountId": { en: "Account ID", ar: "معرّف الحساب" },
  "settings.dangerZone": { en: "Danger Zone", ar: "منطقة الخطر" },
  "settings.irreversibleActions": { en: "Irreversible actions — proceed with caution", ar: "إجراءات لا يمكن التراجع عنها — تصرف بحذر" },
  "settings.deleteAccount": { en: "Delete Account", ar: "حذف الحساب" },
  "settings.deleteAccountDesc": { en: "Permanently delete your account and all data", ar: "حذف حسابك وجميع بياناتك نهائياً" },
  "settings.delete": { en: "Delete", ar: "حذف" },
  "settings.deleting": { en: "Deleting...", ar: "جاري الحذف..." },
  "quiz.settings": { en: "Quiz Settings", ar: "إعدادات الاختبار" },
  "quiz.difficultyLevel": { en: "Difficulty Level", ar: "مستوى الصعوبة" },
  "quiz.auto": { en: "Auto", ar: "تلقائي" },
  "quiz.autoDesc": { en: "AI will automatically adjust difficulty based on your performance", ar: "الذكاء الاصطناعي سيعدّل الصعوبة تلقائياً بناءً على أدائك" },
  "quiz.numberOfQuestions": { en: "Number of Questions", ar: "عدد الأسئلة" },
  "quiz.details": { en: "Quiz Details", ar: "تفاصيل الاختبار" },
  "quiz.estimatedTime": { en: "Estimated Time", ar: "الوقت المتوقع" },
  "quiz.difficulty": { en: "Difficulty", ar: "الصعوبة" },
  "quiz.startQuiz": { en: "Start Quiz", ar: "ابدأ الاختبار" },
  "quiz.min": { en: "min", ar: "دقيقة" },
  "eval.overallScore": { en: "Overall Assessment Score", ar: "درجة التقييم الشاملة" },
  "eval.correctOutOf": { en: "correct out of", ar: "صحيح من أصل" },
  "eval.questionsWord": { en: "questions", ar: "سؤال" },
  "eval.overallAccuracy": { en: "Overall Accuracy", ar: "الدقة الشاملة" },
  "eval.questionsAttempted": { en: "Questions Attempted", ar: "الأسئلة المحاولة" },
  "eval.completionRate": { en: "Completion Rate", ar: "معدل الإكمال" },
  "eval.streak": { en: "Streak", ar: "السلسلة" },
  "eval.strong": { en: "Strong", ar: "ممتاز" },
  "eval.good": { en: "Good", ar: "جيد" },
  "eval.needsWork": { en: "Needs Work", ar: "يحتاج تحسين" },
  "eval.skillMastery": { en: "Skill Mastery", ar: "إتقان المهارات" },
  "eval.skillDesc": { en: "Your proficiency across different skills", ar: "مستوى إتقانك للمهارات المختلفة" },
  "eval.strengths": { en: "Strengths", ar: "نقاط القوة" },
  "eval.improvements": { en: "Areas for Improvement", ar: "مجالات التحسين" },
  "eval.recommendations": { en: "Recommendations", ar: "التوصيات" },
  "eval.viewReport": { en: "View Detailed Report", ar: "عرض التقرير التفصيلي" },
  "eval.retake": { en: "Retake Assessment", ar: "إعادة التقييم" },
  "reports.trackProgress": { en: "Track Your ", ar: "تابع " },
  "reports.progress": { en: "Progress", ar: "تقدمك" },
  "reports.insights": { en: "Get clear insights into your assessments, learning track, and study time", ar: "احصل على رؤى واضحة حول تقييماتك ومسار تعلمك ووقت دراستك" },
  "reports.overallScore": { en: "Overall Assessment Score", ar: "درجة التقييم الشاملة" },
  "reports.avgScore": { en: "Avg. Score", ar: "متوسط الدرجة" },
  "reports.completed": { en: "Completed", ar: "مكتملة" },
  "reports.remaining": { en: "Remaining", ar: "متبقية" },
  "reports.correct": { en: "Correct", ar: "صحيح" },
  "reports.incorrect": { en: "Incorrect", ar: "خاطئ" },
  "reports.noData": { en: "No assessment data yet. Start a quiz!", ar: "لا توجد بيانات تقييم بعد. ابدأ اختباراً!" },
  "reports.learningTrack": { en: "Learning Track Reports", ar: "تقارير مسار التعلم" },
  "reports.sessionsCompleted": { en: "Sessions Completed", ar: "الجلسات المكتملة" },
  "reports.noSessions": { en: "No sessions yet", ar: "لا توجد جلسات بعد" },
  "reports.assessmentReports": { en: "Assessment Reports", ar: "تقارير التقييم" },
  "reports.accuracyLabel": { en: "Accuracy", ar: "الدقة" },
  "reports.noAnswers": { en: "No answers yet", ar: "لا توجد إجابات بعد" },
  "reports.weeklyActivity": { en: "Weekly Activity", ar: "النشاط الأسبوعي" },
  "reports.totalStudyTime": { en: "Total Study Time", ar: "إجمالي وقت الدراسة" },
  "profile.editProfile": { en: "Edit Profile", ar: "تعديل الملف" },
  "profile.saveError": { en: "Failed to save profile.", ar: "فشل حفظ الملف الشخصي." },
  "profile.saveSuccessTitle": { en: "Profile Updated!", ar: "تم تحديث الملف!" },
  "profile.saveSuccessDesc": { en: "Your profile has been saved.", ar: "تم حفظ ملفك الشخصي." },
  "profile.cancelChanges": { en: "Cancel Changes", ar: "إلغاء التعديلات" },
  "profile.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "profile.saveChanges": { en: "Save Changes", ar: "حفظ التعديلات" },
  "profile.myLevel": { en: "My Level", ar: "مستواي" },
  "profile.progressOverview": { en: "Your learning progress overview", ar: "نظرة عامة على تقدمك في التعلم" },
  "profile.viewReport": { en: "View Detailed Report", ar: "عرض التقرير التفصيلي" },
  "profile.overallAccuracy": { en: "Overall Accuracy", ar: "الدقة الشاملة" },
  "profile.questionsCompleted": { en: "Questions Completed", ar: "الأسئلة المكتملة" },
  "profile.learningStreak": { en: "Learning Streak", ar: "سلسلة التعلم" },
  "profile.answered": { en: "answered", ar: "تمت إجابتها" },
  "profile.days": { en: "days", ar: "أيام" },
  "profile.sessions": { en: "sessions", ar: "جلسات" },
  "profile.excellent": { en: "Excellent", ar: "ممتاز" },
  "profile.good": { en: "Good", ar: "جيد" },
  "profile.needsWork": { en: "Needs Work", ar: "يحتاج تحسين" },
  "profile.academicInfo": { en: "Academic Information", ar: "المعلومات الأكاديمية" },
  "profile.educationalDetails": { en: "Your educational details", ar: "تفاصيلك التعليمية" },
  "profile.educationalLevel": { en: "Educational Level", ar: "المستوى التعليمي" },
  "profile.gradeLevel": { en: "Grade/Level", ar: "الصف/المستوى" },
  "profile.aboutMe": { en: "About Me", ar: "عني" },
  "profile.personalInfo": { en: "Personal Information", ar: "المعلومات الشخصية" },
  "profile.personalDetails": { en: "Your basic personal details", ar: "بياناتك الشخصية الأساسية" },
  "profile.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "profile.email": { en: "Email", ar: "البريد الإلكتروني" },
  "profile.phone": { en: "Phone Number", ar: "رقم الهاتف" },
  "profile.location": { en: "Location", ar: "الموقع" },
  "courseDetail.whatIncludes": { en: "What this program includes:", ar: "ما يتضمنه هذا البرنامج:" },
  "courseDetail.reviews": { en: "Reviews:", ar: "المراجعات:" },
  "course.qudurat_verbal": { en: "Qudurat - Verbal", ar: "القدرات - لفظي" },
  "course.qudurat_verbal_desc": { en: "Practice verbal reasoning: reading comprehension, analogies & sentence completion", ar: "تدرّب على التفكير اللفظي: فهم المقروء، التناظر اللفظي وإكمال الجمل" },
  "course.qudurat_quantitative": { en: "Qudurat - Quantitative", ar: "القدرات - كمّي" },
  "course.qudurat_quantitative_desc": { en: "Practice quantitative reasoning: numbers, algebra, geometry & data analysis", ar: "تدرّب على التفكير الكمّي: الأعداد، الجبر، الهندسة وتحليل البيانات" },
  "course.tahseeli_math": { en: "Tahseeli - Mathematics", ar: "التحصيلي - رياضيات" },
  "course.tahseeli_math_desc": { en: "Calculus, algebra, statistics & geometry", ar: "التفاضل والتكامل، الجبر، الإحصاء والهندسة" },
  "course.tahseeli_physics": { en: "Tahseeli - Physics", ar: "التحصيلي - فيزياء" },
  "course.tahseeli_physics_desc": { en: "Mechanics, waves, electricity & modern physics", ar: "الميكانيكا، الموجات، الكهرباء والفيزياء الحديثة" },
  "course.tahseeli_chemistry": { en: "Tahseeli - Chemistry", ar: "التحصيلي - كيمياء" },
  "course.tahseeli_chemistry_desc": { en: "Organic, inorganic & physical chemistry", ar: "الكيمياء العضوية وغير العضوية والفيزيائية" },
  "course.tahseeli_biology": { en: "Tahseeli - Biology", ar: "التحصيلي - أحياء" },
  "course.tahseeli_biology_desc": { en: "Cell biology, genetics, ecology & human anatomy", ar: "علم الخلية، الوراثة، البيئة وتشريح الإنسان" },
  "course.tahseeli_geography": { en: "Tahseeli - Geography", ar: "التحصيلي - جغرافيا" },
  "course.tahseeli_geography_desc": { en: "Human geography, physical geography & maps", ar: "الجغرافيا البشرية والطبيعية والخرائط" },
  "course.tahseeli_arabic": { en: "Tahseeli - Arabic Language", ar: "التحصيلي - اللغة العربية" },
  "course.tahseeli_arabic_desc": { en: "Grammar (Nahw), Literature (Adab), Rhetoric (Balaghah) & Criticism (Naqd)", ar: "النحو والأدب والبلاغة والنقد" },
  "course.tahseeli_islamic": { en: "Tahseeli - Islamic Studies", ar: "التحصيلي - الدروس الإسلامية" },
  "course.tahseeli_islamic_desc": { en: "Tawheed, Fiqh, Hadith & Tafsir", ar: "التوحيد والفقه والحديث والتفسير" },
  "course.ccna": { en: "CCNA", ar: "CCNA" },
  "course.ccna_desc": { en: "Cisco Certified Network Associate — networking fundamentals", ar: "التحضير لشهادة CCNA من سيسكو — أساسيات الشبكات" },
  "course.security_plus": { en: "CompTIA Security+", ar: "CompTIA Security+" },
  "course.security_plus_desc": { en: "Cybersecurity essentials & threat management", ar: "أساسيات الأمن السيبراني وإدارة التهديدات" },
  "course.aws_ccp": { en: "AWS Cloud Practitioner", ar: "AWS Cloud Practitioner" },
  "course.aws_ccp_desc": { en: "AWS cloud concepts, services & billing", ar: "مفاهيم سحابة AWS، الخدمات والفوترة" },
  "course.pmp": { en: "PMP", ar: "PMP" },
  "course.pmp_desc": { en: "Project Management Professional — planning, execution & leadership", ar: "محترف إدارة المشاريع — التخطيط والتنفيذ والقيادة" },
  "badge.beginner": { en: "Beginner", ar: "مبتدئ" },
  "badge.intermediate": { en: "Intermediate", ar: "متوسط" },
  "badge.advanced": { en: "Advanced", ar: "متقدم" },
  "badge.allLevels": { en: "All Levels", ar: "جميع المستويات" },
  "badge.highSchool": { en: "High School", ar: "المرحلة الثانوية" },
  "tag.projectPlanning": { en: "Project Planning", ar: "تخطيط المشاريع" },
  "tag.agileWaterfall": { en: "Agile & Waterfall", ar: "أجايل وووترفول" },
  "tag.riskManagement": { en: "Risk Management", ar: "إدارة المخاطر" },
  "tag.cloudConcepts": { en: "Cloud Concepts", ar: "مفاهيم السحابة" },
  "tag.awsServices": { en: "AWS Services", ar: "خدمات AWS" },
  "tag.securityCompliance": { en: "Security & Compliance", ar: "الأمن والامتثال" },
  "tag.threatManagement": { en: "Threat Management", ar: "إدارة التهديدات" },
  "tag.cryptography": { en: "Cryptography", ar: "التشفير" },
  "tag.riskAssessment": { en: "Risk Assessment", ar: "تقييم المخاطر" },
  "tag.routingSwitching": { en: "Routing & Switching", ar: "التوجيه والتبديل" },
  "tag.ipConnectivity": { en: "IP Connectivity", ar: "الاتصال بـ IP" },
  "tag.networkFundamentals": { en: "Network Fundamentals", ar: "أساسيات الشبكات" },
  "tag.readingComprehension": { en: "Reading Comprehension", ar: "فهم المقروء" },
  "tag.verbalAnalogies": { en: "Verbal Analogies", ar: "التناظر اللفظي" },
  "tag.criticalThinking": { en: "Critical Thinking", ar: "التفكير النقدي" },
  "tag.mathLogic": { en: "Math & Logic", ar: "رياضيات ومنطق" },
  "tag.problemSolving": { en: "Problem Solving", ar: "حل المشكلات" },
  "tag.numericalReasoning": { en: "Numerical Reasoning", ar: "الاستدلال العددي" },
  "tag.algebra": { en: "Algebra", ar: "الجبر" },
  "tag.geometry": { en: "Geometry", ar: "الهندسة" },
  "tag.calculus": { en: "Calculus", ar: "التفاضل والتكامل" },
  "tag.mechanics": { en: "Mechanics", ar: "الميكانيكا" },
  "tag.electricity": { en: "Electricity", ar: "الكهرباء" },
  "tag.waves": { en: "Waves", ar: "الموجات" },
  "tag.organic": { en: "Organic", ar: "عضوي" },
  "tag.reactions": { en: "Reactions", ar: "التفاعلات" },
  "tag.periodicTable": { en: "Periodic Table", ar: "الجدول الدوري" },
  "tag.cells": { en: "Cells", ar: "الخلايا" },
  "tag.genetics": { en: "Genetics", ar: "الوراثة" },
  "tag.ecosystems": { en: "Ecosystems", ar: "النظم البيئية" },
  "tag.physicalGeo": { en: "Physical Geography", ar: "الجغرافيا الطبيعية" },
  "tag.humanGeo": { en: "Human Geography", ar: "الجغرافيا البشرية" },
  "tag.maps": { en: "Maps & Regions", ar: "الخرائط والأقاليم" },
  "tag.grammar": { en: "Grammar (Nahw)", ar: "النحو" },
  "tag.literature": { en: "Literature (Adab)", ar: "الأدب" },
  "tag.rhetoric": { en: "Rhetoric & Criticism", ar: "البلاغة والنقد" },
  "tag.tawheed": { en: "Tawheed", ar: "التوحيد" },
  "tag.fiqh": { en: "Fiqh", ar: "الفقه" },
  "tag.hadith": { en: "Hadith & Tafsir", ar: "الحديث والتفسير" },
  "common.footer": { en: "© 2026 Quizora. All rights reserved.", ar: "© 2026 Quizora. جميع الحقوق محفوظة." },
  "common.error": { en: "Error", ar: "خطأ" },
  "common.success": { en: "Success", ar: "نجاح" },
  "landing.heroDescription": { en: "Experience the future of personalized education. Quizora's advanced AI adapts to your learning style, identifying gaps and accelerating your path to mastery.", ar: "اختبر مستقبل التعليم الشخصي. يتكيّف ذكاء Quizora المتقدم مع أسلوب تعلمك، يكتشف الفجوات ويُسرع طريقك نحو الإتقان." },
  "landing.startFreeTrial": { en: "Start Free Trial", ar: "ابدأ تجربة مجانية" },
  "landing.exploreCourses": { en: "Explore Courses", ar: "استعرض الدورات" },
  "landing.howWorks": { en: "How Quizora Works", ar: "كيف تعمل Quizora" },
  "landing.whyChoose": { en: "Why Choose Quizora", ar: "لماذا تختار Quizora" },
  "landing.premiumFeatures": { en: "Premium Features", ar: "ميزات مميزة" },
  "landing.premiumFeaturesDesc": { en: "Everything you need for accelerated learning and success", ar: "كل ما تحتاجه للتعلم السريع والنجاح" },
  "landing.statsActiveLearners": { en: "Active Learners", ar: "متعلمين نشطين" },
  "landing.statsQuestions": { en: "Questions", ar: "أسئلة" },
  "landing.statsImprovementRate": { en: "Improvement Rate", ar: "معدل التحسن" },
  "landing.statsAvailable": { en: "Available", ar: "متاح" },
  "landing.howWorksStart": { en: "Start Learning", ar: "ابدأ التعلم" },
  "landing.howWorksStartDesc": { en: "Begin solving questions tailored to your knowledge level", ar: "ابدأ حل أسئلة مصممة لمستوى معرفتك" },
  "landing.howWorksAIAnalysis": { en: "AI Analysis", ar: "تحليل الذكاء الاصطناعي" },
  "landing.howWorksAIAnalysisDesc": { en: "Our AI analyzes your performance in real-time", ar: "يقوم الذكاء الاصطناعي بتحليل أدائك في الوقت الحقيقي" },
  "landing.howWorksIdentifyPatterns": { en: "Identify Patterns", ar: "اكتشف الأنماط" },
  "landing.howWorksIdentifyPatternsDesc": { en: "System detects your strengths and learning gaps", ar: "النظام يكتشف نقاط قوتك وفجوات تعلمك" },
  "landing.howWorksAutoAdapt": { en: "Auto Adapt", ar: "التكيف التلقائي" },
  "landing.howWorksAutoAdaptDesc": { en: "Difficulty adjusts automatically to challenge you optimally", ar: "تتكيف الصعوبة تلقائياً لتحديك بشكل مثالي" },
  "landing.howWorksGenerateQuestions": { en: "Generate Questions", ar: "توليد الأسئلة" },
  "landing.howWorksGenerateQuestionsDesc": { en: "Smart system creates personalized questions", ar: "ينشئ النظام الذكي أسئلة مخصصة" },
  "landing.howWorksAchieveMastery": { en: "Achieve Mastery", ar: "حقق الإتقان" },
  "landing.howWorksAchieveMasteryDesc": { en: "Rapid improvement through adaptive learning", ar: "تحسين سريع من خلال التعلم التكيفي" },
  "landing.featuresAI": { en: "AI-Powered Learning", ar: "تعلم مدعوم بالذكاء الاصطناعي" },
  "landing.featuresAIDesc": { en: "Advanced algorithms understand your learning style and adapt in real-time", ar: "خوارزميات متقدمة تفهم أسلوب تعلمك وتتكيّف في الوقت الحقيقي" },
  "landing.featuresPersonalized": { en: "Personalized Paths", ar: "مسارات مخصصة" },
  "landing.featuresPersonalizedDesc": { en: "Custom learning journeys designed specifically for your goals", ar: "رحلات تعليمية مصممة خصيصاً لأهدافك" },
  "landing.featuresAnalytics": { en: "Real-Time Analytics", ar: "تحليلات فورية" },
  "landing.featuresAnalyticsDesc": { en: "Track progress with detailed performance insights and metrics", ar: "تابع تقدمك مع رؤى وأداء مفصّل" },
  "landing.featuresSmart": { en: "Smart Generation", ar: "التوليد الذكي" },
  "landing.featuresSmartDesc": { en: "AI-generated questions that precisely target your learning needs", ar: "أسئلة مولّدة بالذكاء الاصطناعي تستهدف احتياجات تعلمك بدقة" },
  "landing.featuresAdaptive": { en: "Adaptive Difficulty", ar: "صعوبة متكيفة" },
  "landing.featuresAdaptiveDesc": { en: "Stay in the perfect zone of challenge for optimal learning", ar: "ابقَ في منطقة التحدي المثالية للتعلم الأمثل" },
  "landing.featuresSecure": { en: "Secure & Private", ar: "آمن وخاص" },
  "landing.featuresSecureDesc": { en: "Your learning data is protected with enterprise-grade security", ar: "بيانات تعلمك محمية بأمن على مستوى المؤسسات" },
  "landing.finalCtaText": { en: "Join thousands of learners using Quizora to achieve their goals faster and smarter.", ar: "انضم إلى آلاف المتعلمين الذين يستخدمون Quizora لتحقيق أهدافهم بسرعة وذكاء." },
  "landing.viewCourses": { en: "View Courses", ar: "عرض الدورات" },
  "landing.finalCtaTitle": { en: "Ready to Transform Your Learning?", ar: "مستعد لتحويل طريقة تعلمك؟" },
  "landing.startYourFreeTrial": { en: "Start Your Free Trial", ar: "ابدأ تجربتك المجانية" },
  "landing.headline1": { en: "Learn Smarter with", ar: "تعلّم بذكاء مع" },
  "landing.headline2": { en: "Adaptive AI", ar: "الذكاء الاصطناعي المتكيّف" },
  "landing.howWorksDesc": { en: "Our intelligent system learns alongside you, continuously optimizing your learning experience.", ar: "نظامنا الذكي يتعلم معك باستمرار، ويحسّن تجربتك التعليمية بشكل مستمر." },
  "landing.whyChooseDesc": { en: "Built with adaptive learning and clear progress insight to keep you motivated every step of the way.", ar: "مصمم بالتعلم التكيفي ورؤى واضحة للتقدم ليبقيك متحفزاً في كل خطوة." },
  "landing.footerTag": { en: "Powered by advanced AI for personalized learning", ar: "مدعوم بالذكاء الاصطناعي المتقدم للتعلم الشخصي" },
  "courses.scientificTrack": { en: "Scientific Track", ar: "القسم العلمي" },
  "courses.literaryTrack": { en: "Literary Track", ar: "القسم الأدبي" },
  "courses.selectScientific": { en: "Select Scientific", ar: "اختر العلمي" },
  "courses.selectLiterary": { en: "Select Literary", ar: "اختر الأدبي" },
  "courses.scientificSubjects": { en: "Physics • Mathematics • Biology • Chemistry", ar: "فيزياء • رياضيات • أحياء • كيمياء" },
  "courses.literarySubjects": { en: "Geography • Arabic Language • Islamic Studies", ar: "جغرافيا • اللغة العربية • الدروس الإسلامية" },
  "settings.appearance": { en: "Appearance", ar: "المظهر" },
  "settings.chooseTheme": { en: "Choose your theme", ar: "اختر مظهر الموقع" },
  "settings.light": { en: "Light", ar: "نهاري" },
  "settings.dark": { en: "Dark", ar: "ليلي" },
  "settings.passwordFieldsRequired": { en: "Please fill all password fields.", ar: "يرجى ملء جميع حقول كلمة المرور." },
  "settings.passwordsMismatch": { en: "New passwords do not match.", ar: "كلمتا المرور غير متطابقتين." },
  "settings.passwordTooShort": { en: "Password must be at least 6 characters.", ar: "كلمة المرور يجب أن تكون 6 أحرف على الأقل." },
  "settings.passwordUpdatedTitle": { en: "Password Updated!", ar: "تم تحديث كلمة المرور!" },
  "settings.passwordUpdatedDesc": { en: "Your password has been changed successfully.", ar: "تم تغيير كلمة مرورك بنجاح." },
  "settings.preferencesSavedTitle": { en: "Preferences Saved!", ar: "تم حفظ التفضيلات!" },
  "settings.preferencesSavedDesc": { en: "Your notification settings have been updated.", ar: "تم تحديث إعدادات الإشعارات." },
  "settings.deleteConfirm": { en: "Are you sure you want to delete your account? This action cannot be undone.", ar: "هل أنت متأكد من حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء." },
  "settings.accountDeletedTitle": { en: "Account Deleted", ar: "تم حذف الحساب" },
  "settings.accountDeletedDesc": { en: "Your account has been removed.", ar: "تم إزالة حسابك." },
  "notFound.title": { en: "Page Not Found", ar: "الصفحة غير موجودة" },
  "notFound.subtitle": { en: "Sorry, the page you're looking for doesn't exist or has been moved.", ar: "عذراً، الصفحة التي تبحث عنها غير موجودة أو تم نقلها." },
  "notFound.home": { en: "Return to Home", ar: "العودة للرئيسية" },
  "auth.emailSent": { en: "Check your email", ar: "تحقق من بريدك" },
  "auth.passwordsMismatch": { en: "Passwords do not match.", ar: "كلمتا المرور غير متطابقتين." },
  "auth.fillAllFields": { en: "Please fill in all fields.", ar: "يرجى ملء جميع الحقول." },
  "auth.checkEmailVerification": { en: "Please check your email to verify your account.", ar: "يرجى التحقق من بريدك لتأكيد الحساب." },
  "reset.passwordsMismatch": { en: "Passwords do not match.", ar: "كلمتا المرور غير متطابقتين." },
  "reset.tooShort": { en: "Password must be at least 6 characters.", ar: "كلمة المرور يجب أن تكون 6 أحرف على الأقل." },
  "reset.success": { en: "Password updated!", ar: "تم تحديث كلمة المرور!" },
  "reset.updatedSuccess": { en: "You can now sign in with your new password.", ar: "يمكنك الآن تسجيل الدخول باستخدام كلمة المرور الجديدة." },
  "questions.aiNoteTitle": { en: "AI-Powered Generation", ar: "توليد بالذكاء الاصطناعي" },
  "questions.aiNoteDesc": { en: "Questions are generated in real-time and adapt to your level — each question may take a few seconds to load.", ar: "الأسئلة تُولَّد بالوقت الفعلي وتتكيّف مع مستواك — قد يستغرق تحميل كل سؤال بضع ثوانٍ." },
  "questions.aiGenerated": { en: "AI Generated", ar: "مولّد بالذكاء الاصطناعي" },
  "courseDetail.reviews": { en: "Reviews:", ar: "المراجعات:" },
  "courseDetail.writeReview": { en: "Write a Review", ar: "اكتب مراجعة" },
  "courseDetail.signInToReview": { en: "Sign in to write a review", ar: "سجّل دخول لكتابة مراجعة" },
  "courseDetail.shareOpinion": { en: "Share your opinion", ar: "شاركنا رأيك" },
  "courseDetail.overallRating": { en: "Overall Rating", ar: "التقييم العام" },
  "courseDetail.clickToRate": { en: "Click to rate", ar: "اختر تقييمك" },
  "courseDetail.reviewTitle": { en: "Review Title", ar: "عنوان المراجعة" },
  "courseDetail.reviewPlaceholder": { en: "e.g. Amazing experience!", ar: "مثال: تجربة رائعة!" },
  "courseDetail.detailedReview": { en: "Your detailed review", ar: "رأيك بالتفصيل" },
  "courseDetail.detailedPlaceholder": { en: "What did you like? Did it help?", ar: "ماذا أعجبك في هذا البرنامج؟" },
  "courseDetail.postReview": { en: "Submit Review", ar: "نشر المراجعة" },
  "courseDetail.reviewSuccess": { en: "Your review was published successfully ✨", ar: "تم نشر مراجعتك بنجاح ✨" },
  "courseDetail.noReviews": { en: "No reviews yet", ar: "لا توجد مراجعات بعد" },
  "courseDetail.firstReviewer": { en: "Be the first to share your experience!", ar: "كن أول من يشارك رأيه!" },
  "courseDetail.signInFirstReview": { en: "Sign in to write the first review", ar: "سجّل دخول لتكتب أول مراجعة" },
  "courseDetail.writeAReview": { en: "Write a Review", ar: "اكتب مراجعة" },
  "evaluation.heading": { en: "Your Learning Performance", ar: "أداء التعلم الخاص بك" },
  "evaluation.subheading": { en: "Track your progress and performance indicators in a clean page that matches Quizora’s visual identity.", ar: "راقب تقدمك ومؤشرات الأداء في صفحة أنيقة ومتناسقة مع نظام كويزورا." },
  "evaluation.noData": { en: "Start your first training session to see your evaluation and progress here", ar: "ابدأ أول جلسة تدريبية لترى تقييمك ومستواك هنا" },
  "evaluation.startNow": { en: "Start Now", ar: "ابدأ الآن" },
  "evaluation.continueCourse": { en: "Continue Course", ar: "أكمل الكورس" },
  "evaluation.continueWhereLeftOff": { en: "Continue Where You Left Off", ar: "أكمل من حيث توقفت" },
  "evaluation.completed": { en: "Completed", ar: "مكتمل" },
  "evaluation.averageScore": { en: "Average Score", ar: "المعدل العام" },
  "evaluation.activeSessions": { en: "Active Sessions", ar: "جلسات نشطة" },
  "evaluation.viewDetailedReports": { en: "View Detailed Reports", ar: "عرض التقارير التفصيلية" },
  "evaluation.finishedCourses": { en: "You have {count} unfinished course(s)", ar: "لديك {count} دورة غير مكتملة" },
  "evaluation.startedToday": { en: "Started today", ar: "بدأت اليوم" },
  "evaluation.startedYesterday": { en: "Started yesterday", ar: "بدأت أمس" },
  "evaluation.daysAgo": { en: "{days} days ago", ar: "منذ {days} أيام" },
  "evaluation.questions": { en: "Questions", ar: "الأسئلة" },
  "evaluation.correct": { en: "Correct", ar: "صحيحة" },
  "evaluation.wrong": { en: "Wrong", ar: "خاطئة" },
  "evaluation.sessions": { en: "Sessions", ar: "الجلسات" },
  "evaluation.masteryMessage": { en: "Mastery level calculated using BKT algorithm", ar: "مستوى الإتقان محسوب بخوارزمية BKT" },
  "evaluation.retrain": { en: "Retrain", ar: "تدرب مجدداً" },
  "evaluation.noEvaluations": { en: "No Evaluations Yet", ar: "لا يوجد تقييم بعد" },
  "evaluation.reportBtn": { en: "View Detailed Reports", ar: "عرض التقارير التفصيلية" },
  "evaluation.done": { en: "done", ar: "مكتمل" },
  "evaluation.remaining": { en: "remaining", ar: "متبقي" },
  "evaluation.startNow": { en: "Start Now", ar: "ابدأ الآن" },
  "evaluation.continueCourse": { en: "Continue Course", ar: "أكمل الكورس" },
  "evaluation.activeCourseText": { en: "You have {count} unfinished course(s)", ar: "لديك {count} دورة غير مكتملة" },
  "evaluation.perCourseScore": { en: "Your Score Per Course", ar: "نتيجتك لكل كورس" },
  "evaluation.masteryMessage": { en: "Mastery level calculated using BKT algorithm", ar: "مستوى الإتقان محسوب بخوارزمية BKT" },
  "evaluation.retrain": { en: "Retrain", ar: "تدرب مجدداً" },
  "evaluation.viewDetailedReports": { en: "View Detailed Reports", ar: "عرض التقارير التفصيلية" },
  "evaluation.completed": { en: "Completed", ar: "مكتمل" },
  "evaluation.averageScore": { en: "Average Score", ar: "المعدل العام" },
  "evaluation.activeSessions": { en: "Active Sessions", ar: "جلسات نشطة" },
  "evaluation.continueWhereLeftOff": { en: "Continue Where You Left Off", ar: "أكمل من حيث توقفت" },
  "evaluation.answered": { en: "answered", ar: "سؤال أجبت" },
  "evaluation.remaining": { en: "remaining", ar: "متبقي" },
  "evaluation.questions": { en: "questions", ar: "سؤال" },
  "evaluation.startedToday": { en: "Started today", ar: "بدأت اليوم" },
  "evaluation.startedYesterday": { en: "Started yesterday", ar: "بدأت أمس" },
  "evaluation.daysAgo": { en: "{days} days ago", ar: "منذ {days} أيام" },
  "evaluation.level.expert": { en: "Expert", ar: "خبير" },
  "evaluation.level.advanced": { en: "Advanced", ar: "متقدم" },
  "evaluation.level.intermediate": { en: "Intermediate", ar: "متوسط" },
  "evaluation.level.beginner": { en: "Beginner", ar: "مبتدئ" },
  "evaluation.level.newcomer": { en: "Newcomer", ar: "جديد" },
  "evaluation.questions": { en: "Questions", ar: "الأسئلة" },
  "evaluation.correct": { en: "Correct", ar: "صحيحة" },
  "evaluation.wrong": { en: "Wrong", ar: "خاطئة" },
  "evaluation.sessions": { en: "Sessions", ar: "الجلسات" },
  "settings.appearanceTitle": { en: "Appearance", ar: "المظهر" },
  "settings.chooseThemeDesc": { en: "Choose your theme", ar: "اختر مظهر الموقع" },
  "settings.modeLight": { en: "☀️ Light", ar: "☀️ نهاري" },
  "settings.modeDark": { en: "🌙 Dark", ar: "🌙 ليلي" },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  dir: "ltr",
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("quizaura-lang") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("quizaura-lang", lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};