import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<string, Record<Language, string>> = {
  "app.name": { en: "Quizora", ar: "كويزورا" },
  "app.copyright": { en: "© 2026 Quizora. All rights reserved.", ar: "© 2026 كويزورا. جميع الحقوق محفوظة." },
  "common.back": { en: "Back", ar: "رجوع" },
  "common.save": { en: "Save", ar: "حفظ" },
  "common.cancel": { en: "Cancel", ar: "إلغاء" },
  "common.loading": { en: "Loading...", ar: "جاري التحميل..." },
  "common.view": { en: "View", ar: "عرض" },
  "common.start": { en: "Start", ar: "ابدأ" },
  "common.share": { en: "Share", ar: "مشاركة" },
  "common.signOut": { en: "Sign Out", ar: "تسجيل خروج" },
  "common.settings": { en: "Settings", ar: "الإعدادات" },
  "nav.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "nav.learningTrack": { en: "Learning Track", ar: "مسار التعلم" },
  "nav.continueLearning": { en: "Continue Learning", ar: "متابعة التعلم" },
  "nav.results": { en: "Results", ar: "النتائج" },
  "nav.assessments": { en: "Assessments", ar: "التقييمات" },
  "nav.profile": { en: "My Profile", ar: "ملفي الشخصي" },
  "nav.reports": { en: "Reports", ar: "التقارير" },
  "landing.tagline": { en: "Your Path to success starts here", ar: "طريقك نحو النجاح يبدأ من هنا" },
  "landing.headline1": { en: "Professional Certifications & ", ar: "شهادات مهنية و " },
  "landing.headline2": { en: "Aptitude Platform", ar: "منصة اختبارات القدرات" },
  "landing.getStarted": { en: "Get Started", ar: "ابدأ الآن" },
  "landing.exploreLearning": { en: "Explore Learning Track", ar: "استكشف مسار التعلم" },
  "landing.whyChoose": { en: "Why Choose Our ", ar: "لماذا تختار " },
  "landing.platform": { en: "Platform?", ar: "منصتنا؟" },
  "landing.readyToStart": { en: "Ready to Start Your Learning Journey?", ar: "مستعد لبدء رحلة التعلم؟" },
  "landing.signUpFree": { en: "Sign Up for Free", ar: "سجّل مجاناً" },
  "landing.feat1Title": { en: "Professional Certifications", ar: "شهادات مهنية" },
  "landing.feat1Desc": { en: "Get certified in CCNA, Security+, AWS CCP, PMP with comprehensive training programs.", ar: "احصل على شهادات CCNA, Security+, AWS CCP, PMP مع برامج تدريبية شاملة." },
  "landing.feat2Title": { en: "Aptitude & Achievement Tests", ar: "اختبارات القدرات والتحصيلي" },
  "landing.feat2Desc": { en: "Prepare for Qudurat and Tahsili exams with specialized training courses.", ar: "استعد لاختبارات القدرات والتحصيلي مع دورات تدريبية متخصصة." },
  "landing.feat3Title": { en: "Detailed Reports", ar: "تقارير تفصيلية" },
  "landing.feat3Desc": { en: "Track your progress with accurate reports and comprehensive analytics to stay on top of your game.", ar: "تابع تقدمك بتقارير دقيقة وتحليلات شاملة." },
  "auth.accessDashboard": { en: "Access your learning dashboard", ar: "ادخل لوحة التعلم الخاصة بك" },
  "auth.signIn": { en: "Sign In", ar: "تسجيل الدخول" },
  "auth.signUp": { en: "Sign Up", ar: "إنشاء حساب" },
  "auth.welcomeBack": { en: "Welcome Back", ar: "مرحباً بعودتك" },
  "auth.enterCredentials": { en: "Enter your credentials to access your account", ar: "أدخل بياناتك للوصول إلى حسابك" },
  "auth.email": { en: "Email", ar: "البريد الإلكتروني" },
  "auth.password": { en: "Password", ar: "كلمة المرور" },
  "auth.enterEmail": { en: "Enter your email", ar: "أدخل بريدك الإلكتروني" },
  "auth.enterPassword": { en: "Enter your password", ar: "أدخل كلمة المرور" },
  "auth.forgotPassword": { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
  "auth.signingIn": { en: "Signing in...", ar: "جاري تسجيل الدخول..." },
  "auth.orContinueWith": { en: "Or continue with", ar: "أو تابع باستخدام" },
  "auth.createAccount": { en: "Create Account", ar: "إنشاء حساب" },
  "auth.fillDetails": { en: "Fill in your details to get started", ar: "أدخل بياناتك للبدء" },
  "auth.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "auth.enterFullName": { en: "Enter your full name", ar: "أدخل اسمك الكامل" },
  "auth.createPassword": { en: "Create a password", ar: "أنشئ كلمة مرور" },
  "auth.creatingAccount": { en: "Creating account...", ar: "جاري إنشاء الحساب..." },
  "auth.backToHome": { en: "Back to Home", ar: "العودة للرئيسية" },
  "auth.alreadyHaveAccount": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "reset.title": { en: "Reset Password", ar: "إعادة تعيين كلمة المرور" },
  "reset.enterNew": { en: "Enter your new password", ar: "أدخل كلمة المرور الجديدة" },
  "reset.newPassword": { en: "New Password", ar: "كلمة المرور الجديدة" },
  "reset.chooseStrong": { en: "Choose a strong password for your account", ar: "اختر كلمة مرور قوية لحسابك" },
  "reset.confirm": { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  "reset.confirmPlaceholder": { en: "Confirm new password", ar: "أكد كلمة المرور الجديدة" },
  "reset.newPlaceholder": { en: "New password", ar: "كلمة المرور الجديدة" },
  "reset.updating": { en: "Updating...", ar: "جاري التحديث..." },
  "reset.updatePassword": { en: "Update Password", ar: "تحديث كلمة المرور" },
  "dashboard.hub": { en: "Your learning hub", ar: "مركز التعلم الخاص بك" },
  "dashboard.learning": { en: "Learning", ar: "لوحة" },
  "dashboard.title": { en: "Dashboard", ar: "التحكم" },
  "dashboard.chooseOption": { en: "Choose one of the options below to continue your learning journey", ar: "اختر أحد الخيارات أدناه لمتابعة رحلة تعلمك" },
  "dashboard.learningTrack": { en: "Learning Track", ar: "مسار التعلم" },
  "dashboard.learningTrackDesc": { en: "Professional Certifications & Aptitude Tests", ar: "شهادات مهنية واختبارات القدرات" },
  "dashboard.questions": { en: "Questions", ar: "الأسئلة" },
  "dashboard.questionsDesc": { en: "Complete your assessment questionnaire", ar: "أكمل استبيان التقييم" },
  "dashboard.evaluation": { en: "Evaluation", ar: "التقييم" },
  "dashboard.evaluationDesc": { en: "View your scores and AI feedback", ar: "عرض درجاتك وملاحظات الذكاء الاصطناعي" },
  "dashboard.startNow": { en: "Start Now", ar: "ابدأ الآن" },
  "dashboard.continueLearning": { en: "Continue Learning", ar: "تابع تقدمك" },
  "dashboard.resumeWhereYouLeftOff": { en: "Resume where you left off", ar: "أكمل من حيث توقفت" },
  "dashboard.latestCourse": { en: "Continue your latest course", ar: "استمر في آخر دورة بدأت بها" },
  "dashboard.continueCourse": { en: "Continue Course", ar: "أكمل الدورة" },
  "dashboard.continueLearningDesc": { en: "Open the Continue Learning hub to resume any incomplete course.", ar: "افتح مركز المتابعة لاستئناف أي دورة غير مكتملة." },
  "dashboard.chooseCourseToContinue": { en: "Choose a course to continue", ar: "اختر دورة للاستمرار" },
  "dashboard.unfinishedCourses": { en: "unfinished course(s)", ar: "دورة غير مكتملة" },
  "dashboard.noProgressYet": { en: "Start a course to begin tracking progress", ar: "ابدأ دورة لتتبع تقدمك" },
  "dashboard.startNewCourse": { en: "Start a new course to save your progress here.", ar: "ابدأ دورة جديدة لحفظ تقدمك هنا." },
  "dashboard.completed": { en: "Completed", ar: "مكتمل" },
  "dashboard.lastActivity": { en: "Last activity", ar: "آخر نشاط" },
  "dashboard.loadingProgress": { en: "Loading your latest progress...", ar: "تحميل آخر تقدم..." },
  "dashboard.remainingQuestions": { en: "Remaining questions", ar: "الأسئلة المتبقية" },
  "dashboard.complete": { en: "Complete", ar: "مكتمل" },
  "dashboard.reportsAnalytics": { en: "Reports & Analytics", ar: "التقارير والتحليلات" },
  "dashboard.reportsDesc": { en: "View detailed reports and track your progress", ar: "عرض التقارير التفصيلية ومتابعة تقدمك" },
  "dashboard.viewReports": { en: "View Reports", ar: "عرض التقارير" },
  "dashboard.questionsAnswered": { en: "Questions Answered", ar: "أسئلة تم إجابتها" },
  "dashboard.avgScore": { en: "Avg Score", ar: "متوسط الدرجة" },
  "dashboard.studyTime": { en: "Study Time", ar: "وقت الدراسة" },
  "courses.choosePath": { en: "Choose your path", ar: "اختر مسارك" },
  "courses.whatPractice": { en: "What do you want to ", ar: "ماذا تريد أن " },
  "courses.practice": { en: "practice?", ar: "تتدرب عليه؟" },
  "courses.selectCategory": { en: "Select a category to begin your learning journey with adaptive, AI-powered practice.", ar: "اختر فئة لبدء رحلة تعلمك مع تدريب تكيفي مدعوم بالذكاء الاصطناعي." },
  "courses.backToCategories": { en: "Back to categories", ar: "العودة للفئات" },
  "courses.pickSubject": { en: "Pick a subject to start your quiz session.", ar: "اختر مادة لبدء جلسة الاختبار." },
  "courses.available": { en: "courses available", ar: "كورسات متاحة" },
  "courses.getStarted": { en: "Get Started", ar: "ابدأ" },
  "courses.startQuiz": { en: "Start Quiz", ar: "ابدأ الاختبار" },
  "courses.qudurat": { en: "Qudurat", ar: "القدرات" },
  "courses.quduratSub": { en: "General Aptitude Test", ar: "اختبار القدرات العامة" },
  "courses.quduratDesc": { en: "Prepare for the GAT with adaptive practice covering quantitative and verbal reasoning.", ar: "استعد لاختبار القدرات العامة مع تدريب تكيفي يغطي التفكير الكمي واللفظي." },
  "courses.tahseeli": { en: "Tahseeli", ar: "التحصيلي" },
  "courses.tahseeliSub": { en: "Achievement Test", ar: "اختبار التحصيلي" },
  "courses.tahseeliDesc": { en: "Master your subjects with targeted practice for the Saudi Achievement Test.", ar: "أتقن موادك مع تدريب موجّه لاختبار التحصيلي." },
  "courses.certifications": { en: "Professional Certifications", ar: "شهادات مهنية" },
  "courses.certificationsSub": { en: "IT & Management Certs", ar: "شهادات تقنية وإدارية" },
  "courses.certificationsDesc": { en: "Ace industry-leading certifications with expert-curated question banks.", ar: "اجتز الشهادات المهنية الرائدة مع بنوك أسئلة متخصصة." },
  "questions.sessionComplete": { en: "Session Complete! 🎉", ar: "اكتملت الجلسة! 🎉" },
  "questions.questionsLabel": { en: "Questions", ar: "أسئلة" },
  "questions.correct": { en: "Correct", ar: "صحيح" },
  "questions.accuracy": { en: "Accuracy", ar: "الدقة" },
  "questions.backToCourses": { en: "Back to Courses", ar: "العودة للكورسات" },
  "questions.viewReport": { en: "View Report", ar: "عرض التقرير" },
  "questions.adaptiveQuiz": { en: "Adaptive Quiz", ar: "اختبار تكيفي" },
  "questions.endSession": { en: "End Session", ar: "إنهاء الجلسة" },
  "questions.loadingQuestion": { en: "Loading question...", ar: "جاري تحميل السؤال..." },
  "questions.easy": { en: "Easy", ar: "سهل" },
  "questions.medium": { en: "Medium", ar: "متوسط" },
  "questions.hard": { en: "Hard", ar: "صعب" },
  "questions.correctAnswer": { en: "✅ Correct Answer!", ar: "✅ إجابة صحيحة!" },
  "questions.wrongAnswer": { en: "❌ Wrong Answer", ar: "❌ إجابة خاطئة" },
  "questions.generating": { en: "Generating...", ar: "جاري التوليد..." },
  "questions.showExplanation": { en: "Show Explanation", ar: "عرض الشرح" },
  "questions.checking": { en: "Checking...", ar: "جاري التحقق..." },
  "questions.submitAnswer": { en: "Submit Answer", ar: "إرسال الإجابة" },
  "questions.nextQuestion": { en: "Next Question", ar: "السؤال التالي" },
  "settings.title": { en: "Settings", ar: "الإعدادات" },
  "settings.subtitle": { en: "Manage your account preferences", ar: "إدارة تفضيلات حسابك" },
  "settings.language": { en: "Language", ar: "اللغة" },
  "settings.languageDesc": { en: "Choose your preferred language", ar: "اختر لغتك المفضلة" },
  "settings.changePassword": { en: "Change Password", ar: "تغيير كلمة المرور" },
  "settings.updateAccountPassword": { en: "Update your account password", ar: "تحديث كلمة المرور الخاصة بك" },
  "settings.currentPassword": { en: "Current Password", ar: "كلمة المرور الحالية" },
  "settings.enterCurrentPassword": { en: "Enter current password", ar: "أدخل كلمة المرور الحالية" },
  "settings.newPassword": { en: "New Password", ar: "كلمة المرور الجديدة" },
  "settings.enterNewPassword": { en: "Enter new password", ar: "أدخل كلمة المرور الجديدة" },
  "settings.confirmNewPassword": { en: "Confirm New Password", ar: "تأكيد كلمة المرور الجديدة" },
  "settings.confirmNewPasswordPlaceholder": { en: "Confirm new password", ar: "أكد كلمة المرور الجديدة" },
  "settings.updatePassword": { en: "Update Password", ar: "تحديث كلمة المرور" },
  "settings.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "settings.notifications": { en: "Notifications", ar: "الإشعارات" },
  "settings.controlEmails": { en: "Control what emails you receive", ar: "تحكم بالإيميلات التي تصلك" },
  "settings.emailNotifications": { en: "Email Notifications", ar: "إشعارات البريد الإلكتروني" },
  "settings.emailNotificationsDesc": { en: "Receive important updates via email", ar: "استقبل التحديثات المهمة عبر البريد الإلكتروني" },
  "settings.quizReminders": { en: "Quiz Reminders", ar: "تذكيرات الاختبار" },
  "settings.quizRemindersDesc": { en: "Get reminded to practice daily", ar: "احصل على تذكير للتدرب يومياً" },
  "settings.progressReports": { en: "Progress Reports", ar: "تقارير التقدم" },
  "settings.progressReportsDesc": { en: "Weekly summary of your performance", ar: "ملخص أسبوعي لأدائك" },
  "settings.savePreferences": { en: "Save Preferences", ar: "حفظ التفضيلات" },
  "settings.accountInfo": { en: "Account Info", ar: "معلومات الحساب" },
  "settings.yourAccountDetails": { en: "Your account details", ar: "تفاصيل حسابك" },
  "settings.emailAddress": { en: "Email Address", ar: "البريد الإلكتروني" },
  "settings.accountId": { en: "Account ID", ar: "معرّف الحساب" },
  "settings.dangerZone": { en: "Danger Zone", ar: "منطقة الخطر" },
  "settings.irreversibleActions": { en: "Irreversible actions — proceed with caution", ar: "إجراءات لا يمكن التراجع عنها — تصرف بحذر" },
  "settings.deleteAccount": { en: "Delete Account", ar: "حذف الحساب" },
  "settings.deleteAccountDesc": { en: "Permanently delete your account and all data", ar: "حذف حسابك وجميع بياناتك نهائياً" },
  "settings.delete": { en: "Delete", ar: "حذف" },
  "settings.deleting": { en: "Deleting...", ar: "جاري الحذف..." },
  "quiz.settings": { en: "Quiz Settings", ar: "إعدادات الاختبار" },
  "quiz.difficultyLevel": { en: "Difficulty Level", ar: "مستوى الصعوبة" },
  "quiz.auto": { en: "Auto", ar: "تلقائي" },
  "quiz.autoDesc": { en: "AI will automatically adjust difficulty based on your performance", ar: "الذكاء الاصطناعي سيعدّل الصعوبة تلقائياً بناءً على أدائك" },
  "quiz.numberOfQuestions": { en: "Number of Questions", ar: "عدد الأسئلة" },
  "quiz.details": { en: "Quiz Details", ar: "تفاصيل الاختبار" },
  "quiz.estimatedTime": { en: "Estimated Time", ar: "الوقت المتوقع" },
  "quiz.difficulty": { en: "Difficulty", ar: "الصعوبة" },
  "quiz.startQuiz": { en: "Start Quiz", ar: "ابدأ الاختبار" },
  "quiz.min": { en: "min", ar: "دقيقة" },
  "eval.overallScore": { en: "Overall Assessment Score", ar: "درجة التقييم الشاملة" },
  "eval.correctOutOf": { en: "correct out of", ar: "صحيح من أصل" },
  "eval.questionsWord": { en: "questions", ar: "سؤال" },
  "eval.overallAccuracy": { en: "Overall Accuracy", ar: "الدقة الشاملة" },
  "eval.questionsAttempted": { en: "Questions Attempted", ar: "الأسئلة المحاولة" },
  "eval.completionRate": { en: "Completion Rate", ar: "معدل الإكمال" },
  "eval.streak": { en: "Streak", ar: "السلسلة" },
  "eval.strong": { en: "Strong", ar: "ممتاز" },
  "eval.good": { en: "Good", ar: "جيد" },
  "eval.needsWork": { en: "Needs Work", ar: "يحتاج تحسين" },
  "eval.skillMastery": { en: "Skill Mastery", ar: "إتقان المهارات" },
  "eval.skillDesc": { en: "Your proficiency across different skills", ar: "مستوى إتقانك للمهارات المختلفة" },
  "eval.strengths": { en: "Strengths", ar: "نقاط القوة" },
  "eval.improvements": { en: "Areas for Improvement", ar: "مجالات التحسين" },
  "eval.recommendations": { en: "Recommendations", ar: "التوصيات" },
  "eval.viewReport": { en: "View Detailed Report", ar: "عرض التقرير التفصيلي" },
  "eval.retake": { en: "Retake Assessment", ar: "إعادة التقييم" },
  "reports.trackProgress": { en: "Track Your ", ar: "تابع " },
  "reports.progress": { en: "Progress", ar: "تقدمك" },
  "reports.insights": { en: "Get clear insights into your assessments, learning track, and study time", ar: "احصل على رؤى واضحة حول تقييماتك ومسار تعلمك ووقت دراستك" },
  "reports.overallScore": { en: "Overall Assessment Score", ar: "درجة التقييم الشاملة" },
  "reports.avgScore": { en: "Avg. Score", ar: "متوسط الدرجة" },
  "reports.noData": { en: "No assessment data yet. Start a quiz!", ar: "لا توجد بيانات تقييم بعد. ابدأ اختباراً!" },
  "reports.learningTrack": { en: "Learning Track Reports", ar: "تقارير مسار التعلم" },
  "reports.sessionsCompleted": { en: "Sessions Completed", ar: "الجلسات المكتملة" },
  "reports.noSessions": { en: "No sessions yet", ar: "لا توجد جلسات بعد" },
  "reports.assessmentReports": { en: "Assessment Reports", ar: "تقارير التقييم" },
  "reports.accuracyLabel": { en: "Accuracy", ar: "الدقة" },
  "reports.noAnswers": { en: "No answers yet", ar: "لا توجد إجابات بعد" },
  "reports.weeklyActivity": { en: "Weekly Activity", ar: "النشاط الأسبوعي" },
  "reports.totalStudyTime": { en: "Total Study Time", ar: "إجمالي وقت الدراسة" },
  "profile.editProfile": { en: "Edit Profile", ar: "تعديل الملف" },
  "profile.cancelChanges": { en: "Cancel Changes", ar: "إلغاء التعديلات" },
  "profile.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "profile.saveChanges": { en: "Save Changes", ar: "حفظ التعديلات" },
  "profile.myLevel": { en: "My Level", ar: "مستواي" },
  "profile.progressOverview": { en: "Your learning progress overview", ar: "نظرة عامة على تقدمك في التعلم" },
  "profile.viewReport": { en: "View Detailed Report", ar: "عرض التقرير التفصيلي" },
  "profile.overallAccuracy": { en: "Overall Accuracy", ar: "الدقة الشاملة" },
  "profile.questionsCompleted": { en: "Questions Completed", ar: "الأسئلة المكتملة" },
  "profile.learningStreak": { en: "Learning Streak", ar: "سلسلة التعلم" },
  "profile.answered": { en: "answered", ar: "تمت إجابتها" },
  "profile.days": { en: "days", ar: "أيام" },
  "profile.sessions": { en: "sessions", ar: "جلسات" },
  "profile.excellent": { en: "Excellent", ar: "ممتاز" },
  "profile.good": { en: "Good", ar: "جيد" },
  "profile.needsWork": { en: "Needs Work", ar: "يحتاج تحسين" },
  "profile.academicInfo": { en: "Academic Information", ar: "المعلومات الأكاديمية" },
  "profile.educationalDetails": { en: "Your educational details", ar: "تفاصيلك التعليمية" },
  "profile.educationalLevel": { en: "Educational Level", ar: "المستوى التعليمي" },
  "profile.gradeLevel": { en: "Grade/Level", ar: "الصف/المستوى" },
  "profile.aboutMe": { en: "About Me", ar: "عني" },
  "profile.personalInfo": { en: "Personal Information", ar: "المعلومات الشخصية" },
  "profile.personalDetails": { en: "Your basic personal details", ar: "بياناتك الشخصية الأساسية" },
  "profile.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "profile.email": { en: "Email", ar: "البريد الإلكتروني" },
  "profile.phone": { en: "Phone Number", ar: "رقم الهاتف" },
  "profile.location": { en: "Location", ar: "الموقع" },
  "courseDetail.whatIncludes": { en: "What this program includes:", ar: "ما يتضمنه هذا البرنامج:" },
  "courseDetail.reviews": { en: "Reviews:", ar: "المراجعات:" },
  "course.qudurat_verbal": { en: "Qudurat - Verbal", ar: "القدرات - لفظي" },
  "course.qudurat_verbal_desc": { en: "Practice verbal reasoning: reading comprehension, analogies & sentence completion", ar: "تدرّب على التفكير اللفظي: فهم المقروء، التناظر اللفظي وإكمال الجمل" },
  "course.qudurat_quantitative": { en: "Qudurat - Quantitative", ar: "القدرات - كمّي" },
  "course.qudurat_quantitative_desc": { en: "Practice quantitative reasoning: numbers, algebra, geometry & data analysis", ar: "تدرّب على التفكير الكمّي: الأعداد، الجبر، الهندسة وتحليل البيانات" },
  "course.tahseeli_math": { en: "Tahseeli - Mathematics", ar: "التحصيلي - رياضيات" },
  "course.tahseeli_math_desc": { en: "Calculus, algebra, statistics & geometry", ar: "التفاضل والتكامل، الجبر، الإحصاء والهندسة" },
  "course.tahseeli_physics": { en: "Tahseeli - Physics", ar: "التحصيلي - فيزياء" },
  "course.tahseeli_physics_desc": { en: "Mechanics, waves, electricity & modern physics", ar: "الميكانيكا، الموجات، الكهرباء والفيزياء الحديثة" },
  "course.tahseeli_chemistry": { en: "Tahseeli - Chemistry", ar: "التحصيلي - كيمياء" },
  "course.tahseeli_chemistry_desc": { en: "Organic, inorganic & physical chemistry", ar: "الكيمياء العضوية وغير العضوية والفيزيائية" },
  "course.tahseeli_biology": { en: "Tahseeli - Biology", ar: "التحصيلي - أحياء" },
  "course.tahseeli_biology_desc": { en: "Cell biology, genetics, ecology & human anatomy", ar: "علم الخلية، الوراثة، البيئة وتشريح الإنسان" },
  "course.tahseeli_geography": { en: "Tahseeli - Geography", ar: "التحصيلي - جغرافيا" },
  "course.tahseeli_geography_desc": { en: "Human geography, physical geography & maps", ar: "الجغرافيا البشرية والطبيعية والخرائط" },
  "course.tahseeli_arabic": { en: "Tahseeli - Arabic Language", ar: "التحصيلي - اللغة العربية" },
  "course.tahseeli_arabic_desc": { en: "Grammar (Nahw), Literature (Adab), Rhetoric (Balaghah) & Criticism (Naqd)", ar: "النحو والأدب والبلاغة والنقد" },
  "course.tahseeli_islamic": { en: "Tahseeli - Islamic Studies", ar: "التحصيلي - الدروس الإسلامية" },
  "course.tahseeli_islamic_desc": { en: "Tawheed, Fiqh, Hadith & Tafsir", ar: "التوحيد والفقه والحديث والتفسير" },
  "course.ccna": { en: "CCNA", ar: "CCNA" },
  "course.ccna_desc": { en: "Cisco Certified Network Associate — networking fundamentals", ar: "التحضير لشهادة CCNA من سيسكو — أساسيات الشبكات" },
  "course.security_plus": { en: "CompTIA Security+", ar: "CompTIA Security+" },
  "course.security_plus_desc": { en: "Cybersecurity essentials & threat management", ar: "أساسيات الأمن السيبراني وإدارة التهديدات" },
  "course.aws_ccp": { en: "AWS Cloud Practitioner", ar: "AWS Cloud Practitioner" },
  "course.aws_ccp_desc": { en: "AWS cloud concepts, services & billing", ar: "مفاهيم سحابة AWS، الخدمات والفوترة" },
  "course.pmp": { en: "PMP", ar: "PMP" },
  "course.pmp_desc": { en: "Project Management Professional — planning, execution & leadership", ar: "محترف إدارة المشاريع — التخطيط والتنفيذ والقيادة" },
  "badge.beginner": { en: "Beginner", ar: "مبتدئ" },
  "badge.intermediate": { en: "Intermediate", ar: "متوسط" },
  "badge.advanced": { en: "Advanced", ar: "متقدم" },
  "badge.allLevels": { en: "All Levels", ar: "جميع المستويات" },
  "badge.highSchool": { en: "High School", ar: "المرحلة الثانوية" },
  "tag.projectPlanning": { en: "Project Planning", ar: "تخطيط المشاريع" },
  "tag.agileWaterfall": { en: "Agile & Waterfall", ar: "أجايل وووترفول" },
  "tag.riskManagement": { en: "Risk Management", ar: "إدارة المخاطر" },
  "tag.cloudConcepts": { en: "Cloud Concepts", ar: "مفاهيم السحابة" },
  "tag.awsServices": { en: "AWS Services", ar: "خدمات AWS" },
  "tag.securityCompliance": { en: "Security & Compliance", ar: "الأمن والامتثال" },
  "tag.threatManagement": { en: "Threat Management", ar: "إدارة التهديدات" },
  "tag.cryptography": { en: "Cryptography", ar: "التشفير" },
  "tag.riskAssessment": { en: "Risk Assessment", ar: "تقييم المخاطر" },
  "tag.routingSwitching": { en: "Routing & Switching", ar: "التوجيه والتبديل" },
  "tag.ipConnectivity": { en: "IP Connectivity", ar: "الاتصال بـ IP" },
  "tag.networkFundamentals": { en: "Network Fundamentals", ar: "أساسيات الشبكات" },
  "tag.readingComprehension": { en: "Reading Comprehension", ar: "فهم المقروء" },
  "tag.verbalAnalogies": { en: "Verbal Analogies", ar: "التناظر اللفظي" },
  "tag.criticalThinking": { en: "Critical Thinking", ar: "التفكير النقدي" },
  "tag.mathLogic": { en: "Math & Logic", ar: "رياضيات ومنطق" },
  "tag.problemSolving": { en: "Problem Solving", ar: "حل المشكلات" },
  "tag.numericalReasoning": { en: "Numerical Reasoning", ar: "الاستدلال العددي" },
  "tag.algebra": { en: "Algebra", ar: "الجبر" },
  "tag.geometry": { en: "Geometry", ar: "الهندسة" },
  "tag.calculus": { en: "Calculus", ar: "التفاضل والتكامل" },
  "tag.mechanics": { en: "Mechanics", ar: "الميكانيكا" },
  "tag.electricity": { en: "Electricity", ar: "الكهرباء" },
  "tag.waves": { en: "Waves", ar: "الموجات" },
  "tag.organic": { en: "Organic", ar: "عضوي" },
  "tag.reactions": { en: "Reactions", ar: "التفاعلات" },
  "tag.periodicTable": { en: "Periodic Table", ar: "الجدول الدوري" },
  "tag.cells": { en: "Cells", ar: "الخلايا" },
  "tag.genetics": { en: "Genetics", ar: "الوراثة" },
  "tag.ecosystems": { en: "Ecosystems", ar: "النظم البيئية" },
  "tag.physicalGeo": { en: "Physical Geography", ar: "الجغرافيا الطبيعية" },
  "tag.humanGeo": { en: "Human Geography", ar: "الجغرافيا البشرية" },
  "tag.maps": { en: "Maps & Regions", ar: "الخرائط والأقاليم" },
  "tag.grammar": { en: "Grammar (Nahw)", ar: "النحو" },
  "tag.literature": { en: "Literature (Adab)", ar: "الأدب" },
  "tag.rhetoric": { en: "Rhetoric & Criticism", ar: "البلاغة والنقد" },
  "tag.tawheed": { en: "Tawheed", ar: "التوحيد" },
  "tag.fiqh": { en: "Fiqh", ar: "الفقه" },
  "tag.hadith": { en: "Hadith & Tafsir", ar: "الحديث والتفسير" },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  dir: "ltr",
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("quizaura-lang") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("quizaura-lang", lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};